### ISSUE TITLE
Database deletion: Pending immediate removal shown

### ISSUE THREAD

**Issue by sorin-pop** [djavorszky/ddn#80] opened 2017-04-06 16:48 UTC
There seems to be something wrong on the UI when dropping a database. Its record stays in the list as Pending immediate removal.

**Comment by djavorszky** [comment] 2017-04-06 17:02
That's intended, the result of #49 - in order to be able to drop the database in an async way, I wanted to update the status to something.

Maybe the wording isn't the best, it could say "Database being dropped", but at that time the wording seemed to be fine.

**Comment by djavorszky** [comment] 2017-04-06 17:50
Except if it times out, in which case I'm not sure what would happen. I'll probably have to revisit it.

**Comment by sorin-pop** [comment] 2017-04-07 09:33
Yes, I think the wording is a little cryptic, I like better "Database being dropped". 

But the main problem is that, as I experienced, the record stays there in that status even after the database has been dropped in the background. It does not disappear.

**Comment by sorin-pop** [comment] 2017-04-07 09:41
One more info, maybe it helps: I did not drop huge databases, but small ones, even empty ones. So I don't think the timeout stuff played a role in my case.

**Comment by djavorszky** [comment] 2017-04-07 09:54
Ok, let's rename it.

As for it staying there, if you're dropping small databases, after a refresh, it should disappear. If it doesn't, then something may have gone wrong. Basically what I did was I moved the "connector please drop the database x" into a goroutine, at the end of which the local database was updated.

The record will not be removed if, during dropping the database, either the connector or the server dies.

Did this happen? Or can you reproduce it in any way?

**Comment by sorin-pop** [comment] 2017-04-07 10:04
The connector or server did not die. I only noticed this with mssql databases, while testing. I did not try with other type. Maybe it's something wrong with my mssql drop implementation. I'll further test this and let you know.

**Comment by djavorszky** [comment] 2017-04-07 11:04
In that case, you should see some log entry on the server:
     
    func dropAsync(conn model.Connector, ID int, dbname, dbuser string) {
	_, err := conn.DropDatabase(ID, dbname, dbuser)
	if err != nil {
		log.Printf("Couldn't drop database %q on connector %q: %s", dbname, conn.ShortName, err.Error())
		return
	}

	db.delete(int64(ID))
    }

err is {{nil}} if the connector replies with any of the following: {{status.Success, status.Accepted, status.Started, status.Created}}, otherwise, it fails out.

That said, looking at the implementation, if it fails out, the status is left at "Pending immediate drop", so that should also be updated.

@sorin-pop, want to tackle this issue, or want me to take a jab at it?

**Comment by sorin-pop** [comment] 2017-04-07 17:23
I think there was some issue with my code as well, in the end it worked fine. But I think you are right that if it fails, it gets stuck in that status, so this could be further improved. I'll try myself at tackling it and I'll let you know.

**Comment by sorin-pop** [comment] 2017-04-11 08:25
Let's deal with this if it will really be occurring a lot, and thus will be annoying. Theoretically, the drop database action is a very simple one, there are not many things that can go wrong here. That's why it is also difficult to reproduce and test this scenario. I encountered it for a while, while testing mssql, but after I gave a certain permission, role to the clouddb user, the problem disappeared.

I would say let's close this ticket for now and we'll see if we really need to handle this in the future. What do you say?

**Comment by djavorszky** [comment] 2017-04-11 08:34
You are right, dropping is easy - the problem comes with the environment. Imagine if dropping a ~10 Gb database takes 30+ seconds - at which point the network decides to drop the connection. In this case, we'd get an error and the record would stay as it is.

Updating this should be easy - in the error section, just update the status to "status.DropFailed" (and add that to the status package). That said, I think we can go further, but that would require #48 first - that way, we'd be able to also persist the reason why the drop failed.

So, at this point, I'd say let's wait a bit until #48 is implemented - I'll start working on that right now.

**Comment by djavorszky** [comment] 2017-04-13 11:34
Resolved by 28438d7

**Closed by djavorszky** 2017-04-13 11:34 UTC
Labels: enhancement
