### ISSUE TITLE
Use statement not removed from dump

### ISSUE THREAD

**Issue by alfonsocrisci** [djavorszky/ddn#199] opened 2017-09-21 12:04 UTC
> Import database failed
> 
> Your request to import a(n) "mysql" database named "digital_system" has failed with the following message:
> 
> "Importing dump failed: could not execute import command: mysql: [Warning] Using a password on the command line interface can be insecure.\nERROR 1044 (42000) at line 1: Access denied for user 'tag_receiver'@'%' to database 'liferay'"
> 
> We're sorry for the inconvenience caused.
> 
> Visit Cloud DB.

Sorry if I don't add anything more and check for already open tickets/duplicates. Please let me know in case of questions.

Thanks !

**Comment by djavorszky** [comment] 2017-09-27 08:14
as I can see, the issue is the same as before: there's a 'use database' somewhere that is not being removed.

**Comment by djavorszky** [comment] 2017-09-27 09:35
Dump starts with the following statements:
```
$ head dbdump.sql 
CREATE DATABASE  IF NOT EXISTS `liferay` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `liferay`;
-- MySQL dump 10.13  Distrib 5.6.24, for Win32 (x86)
```

Both the create database and use statements should have been removed in mysql's [ValidateDump](https://github.com/djavorszky/ddn/blob/master/connector/mysql.go#L334-L366) method. It uses sutils.OccursWith(strings.HasPrefix), for which there's a test already - this use case [should be covered](https://github.com/djavorszky/sutils/blob/master/strings_test.go#L303-L353)...

**Comment by djavorszky** [comment] 2017-09-27 09:36
Trunk doesn't even import the database in the dump, so something's off there. Need to dig in.

**Comment by djavorszky** [comment] 2017-09-27 13:56
Issue fixed on master - at least with the dumpfile that Alfonso shared. I'll do a release soon; will keep this issue open until then.

**Comment by djavorszky** [comment] 2017-10-02 12:56
@alfonsocrisci, happy to say that the connector has been updated (mysql-55, mysql-56 so far, working on mysql-57), it now removes the use statements from the dump.

Cheers!
Dani

**Comment by alfonsocrisci** [comment] 2017-10-02 12:57
Thanks !

**Closed by djavorszky** 2017-10-02 12:56 UTC
Labels: bug
